---

language: python

services:
  - docker

install:
  - pip install ansible

script:

  # Install dependencies
  - ansible-galaxy install -r requirements.yml

  # Check syntax
  - ansible-playbook local.yml --syntax-check
