---

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  matrix:
    - MOLECULE_DISTRO: centos:7
    - MOLECULE_DISTRO: fedora:28
    - MOLECULE_DISTRO: fedora:31

install:
  - pip install ansible docker

script:

  # Install dependencies
  - ansible-galaxy install -r requirements.yml

  # Check syntax
  - ansible-playbook local.yml --syntax-check

  # Test the entire playbook
  - ansible-playbook local.yml -K
