
# Installs and configures Zsh using Oh-My-Zsh

- name: Install ZSH
  package:
          name: zsh 
          state: latest
  become: yes


- name: Set zsh as default shell
  user:
          name: "{{ ansible_ssh_user }}"
          shell: /bin/zsh
  become: yes
  

- name: Create temporary directory
  file:
          path: ~/tmp
          state: directory
          

- name: Download oh-my-zsh
  get_url:
          url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh          
          dest: ~/tmp/install-oh-my-zsh.sh
          mode: 0755 # Makes retrieved files executable


- name: Install oh-my-zsh 
  command: 
          cmd: zsh ~/tmp/install-oh-my-zsh.sh
          creates: ~/.oh-my-zsh


- name: Place zshrc in home directory
  copy: 
        src: zshrc
        dest: ~/.zshrc  


- name: Install zsh-syntax-highlighting
  git:
          repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
          dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
