
# Installs spotify from the negativo repository


- name: Adding spotify client repository
  command:
          cmd: dnf config-manager --add-repo=https://negativo17.org/repos/fedora-spotify.repo
  become: yes
  
  
- name: Install spotify client from negativo
  package:
          name: spotify-client 
          state: latest
  become: yes
