
# Installs and configures vim, with all its dotfiles

- name: Install vim if it isn't already installed
  package:
          name: vim-enhanced
          state: latest
  become: yes


- name: Place vimrc in home directory
  copy: 
        src: vimrc
        dest: ~/.vimrc
        
        
- name: Installing vundle for plugin management
  git: 
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        

# For now it's necessary to install plugins by hand

#- name: Install Vundle plugins for vim
#  shell: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty
