
# Installs and configures vim, with all its dotfiles

- name: Install vim if it isn't already installed
  package:
          name: vim-enhanced
          state: latest
  become: yes


- name: Place vimrc in home directory
  copy: 
        src: vimrc
        dest: ~/.vimrc
        
        
- name: Add the colors directory
  file:
          path: ~/.vim/colors
          state: directory
          

- name: Add the solarized color scheme
  copy: 
        src: solarized.vim
        dest: ~/.vim/colors/solarized.vim
        
        
- name: Installing vundle for plugin management
  git: 
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        
        
- name: Add the youCompleteMe configuration file
  copy: 
        src: youCompleteMe.conf
        dest: ~/.vim/.ycm_extra_conf.py


- name: Install prerequisites for youCompleteMe compilation
  package: name={{item}} state=latest
  with_items:
       - cmake
       - make 
       - python3-devel
       - gcc-c++
  become: yes
        
        
- name: Installing youCompleteMe
  shell: 
        cmd: python3 install.py --clang-completer
        chdir: ~/.vim/bundle/youcompleteme
        
        
# For now it's necessary to install plugins by hand

#- name: Install Vundle plugins for vim
#  shell: vim +'PlugInstall --sync' +qall &> /dev/null < /dev/tty
