
# Configures my terminal settings using dconf


- name: Create temporary directory
  file:
          path: ~/tmp
          state: directory
          
          
- name: Place terminal config file in home directory
  copy: 
        src: gnome-terminal-settings.txt
        dest: ~/tmp/gnome-terminal-settings.dconf
        
        
- name: Load dconf file of gnome-terminal
  command: 
          cmd: "dconf load /org/gnome/terminal/ < ~/tmp/gnome-terminal-settings.dconf"
          chdir: ~/tmp
